#lang racket

(require "simpleLanguageInterpreter.rkt")

(run-program "tests/test1.txt")
(run-program "tests/test2.txt")
(run-program "tests/test3.txt")
(run-program "tests/test4.txt")
(run-program "tests/test5.txt")
(run-program "tests/test6.txt")
(run-program "tests/test7.txt")
(run-program "tests/test8.txt")
(run-program "tests/test9.txt")
(run-program "tests/test10.txt")
;(run-program "tests/test11.txt")
;(run-program "tests/test12.txt")
;(run-program "tests/test13.txt")
;(run-program "tests/test14.txt")
(run-program "tests/test15.txt")
(run-program "tests/test16.txt")
(run-program "tests/test17.txt")
(run-program "tests/test18.txt")
(run-program "tests/test19.txt")
(run-program "tests/test20.txt")

